// Auto-generated from Goodreads RSS (shelf: read). Do not edit by hand.
// Source: https://www.goodreads.com/user/show/190975958-mark-lyons
const BOOKS = [
  {
    "title": "Project Hail Mary",
    "author": "Andy Weir",
    "rating": 3,
    "review": "This book felt like it was written by an LLM trained only on Reddit, the dialogue can be really cringey. A lot of the science parts feel very tedious. Rocky does a lot of the heavy lifting in making this still a fun story and worth going through. I think this will be far better as a movie so I look forward to that.",
    "cover": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1764703833l/54493401._SY475_.jpg",
    "link": "https://www.goodreads.com/review/show/8627321974",
    "readAt": "Tue, 26 May 2026 00:00:00 +0000",
    "year": "2021",
    "pages": "476",
    "color": "#7c2d2d",
    "thickness": 45,
    "yearRead": "2026"
  },
  {
    "title": "East of Eden",
    "author": "John Steinbeck",
    "rating": 5,
    "review": "Just about perfect. I have never had a book strike me as immediately as this did. Within the first few pages, certainly in 20 pages, it is clear that it is something truly special and at no point does the story betray that. This is an essential read and I'm a bit ashamed that this took me so long to discover.<br /><br />When I was nearing the end, I started making a plan to make the last few chapters more memorable by reading the ending at some significant spot in Steinbeck's life in New York. I found that he primarily wrote this at 206 E 72nd St in Manhattan. His particular building was long gone, but his former neighbors' townhomes stood proudly modeling to me what his home would have looked like. To speak of his neighbors, they had a nice fence, suitable for leaning on while reading, standing where his front steps may have once been. This was useful because the only spot to sit was the bus stop which seemed to have been a popular place for four-legged creatures to find relief. <br /><br />Putting aside the sappiness of hopping on the subway just to be where a book may or may not have been written, I was skeptical that he actually wrote it there, as he only moved to that location in 1951 and East of Eden was published in 1952. I was thinking he may have only written a few of the last chapters here, or just made some edits. The Penguin Classics edition I read clarified this with letters to his editor at the end of the final chapter:<br /><blockquote>January 29, 1951<br /><br />... and in two days I am moving into the pretty little house on 72nd St. and there I will have a room to work in and I will have love all around me. Maybe I can finally write the book.</blockquote><br /><br />I was feeling better about my excessive sentimentality after reading that while leaning against his neighbor's fence. The next letters chronicle the following 6 months, writing at an incredible pace while thinking he was going too fast or too slow. <br /><br />This book is a wealth of important lessons too numerous to begin to list. The beautiful thing about books like these is that you often think you will get these lessons from parents, grandparents, a wise older brother -- and it just doesn't happen. One can be easily tricked into thinking you should've emerged into adult life having learned the important lessons directly from family, but the truth is that you have to learn them yourself. A book like this will meet you where you are and dispense wisdom you didn't know you needed. No two readers digest the same book because they each needed different lessons to extract from story. There are enough meaningful facts about life in East of Eden that it will soothe whatever it is you face.<br /><br /><blockquote>You're going to pass something down no matter what you do or if you do nothing. Even if you let yourself go fallow, the weeds will grow and the brambles. Something will grow.</blockquote><br /><br />Samuel Hamilton is my favorite character I have discovered in literature so far and I suspect very few will come close. At points he dominates the dialogue and focus and it still isn't enough. Having finished the book, and thinking back to what really struck me while standing in front of a dentist at the site of the author's former home, I recalled:<br /><br /><blockquote>And while I tell you, I am myself sifting my memories, the way men pan the dirt under a barroom floor for the bits of gold dust that fall between the cracks. It’s small mining -- small mining. You're too young a man to be panning memories, Adam. You should be getting yourself some new ones, so that the mining will be richer when you come to age.</blockquote><br /><br />I decided that it was time to walk away. And off to the west there was a just about perfect sunset.",
    "cover": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1747251534l/883438._SY475_.jpg",
    "link": "https://www.goodreads.com/review/show/8596594652",
    "readAt": "Thu, 21 May 2026 00:00:00 +0000",
    "year": "1952",
    "pages": "602",
    "color": "#2d4a3e",
    "thickness": 51,
    "yearRead": "2026"
  },
  {
    "title": "The Leopard",
    "author": "Giuseppe Tomasi di Lampedusa",
    "rating": 4,
    "review": "I liked it. I mostly enjoyed the first/main story which contained a profound sense of how much life can feel like it is missing something undefined that can only really be communicated well by someone like the author and the subject he was writing about — aristocracy who have every need met.<br /><br />I found the passing of one character very moving. In an earlier segment of the book he asks Venus when he will be given a more meaningful assignment than this life, and Venus comes to him as a woman in the final moments of his life, described quite beautifully by the author. <br /><br />I also really enjoyed the standalone story where the author befriends Senator La Curia and we get a retelling of a famous mystical story. <br /><br />I think Tomasi would’ve written a spectacular fantasy novel but it seems clear from the focus of what he did write that his writing interests were elsewhere.",
    "cover": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1590069320l/53455050._SY475_.jpg",
    "link": "https://www.goodreads.com/review/show/8545789933",
    "readAt": "Sun, 10 May 2026 00:00:00 +0000",
    "year": "1958",
    "pages": "248",
    "color": "#2c3e50",
    "thickness": 35,
    "yearRead": "2026"
  },
  {
    "title": "The Oresteia: Agamemnon, Choephoroe, Eumenides",
    "author": "Aeschylus",
    "rating": 5,
    "review": "In April 1968, RFK famously spoke to a crowd in Indianapolis announcing the assassination of Martin Luther King. My feeling is that it is some of the best spoken word in the history of the English language. So well chosen were RFK’s words (chosen more or less on the spot) that they resonate many decades later and Indianapolis was one of the only major cities in the US that did not riot that night. <br /><blockquote>For those of you who are black and are tempted to fill with hatred and mistrust of the injustice of such an act, against all white people, I would only say that I can also feel in my own heart the same kind of feeling. I had a member of my family killed, but he was killed by a white man.<br /><br />But we have to make an effort in the United States. We have to make an effort to understand, to get beyond, or go beyond these rather difficult times.<br /><br />My favorite poet was Aeschylus. And he once wrote:</blockquote><br /><br />And I will first give you the quote that was shown in my copy, the Everyman’s Library edition translated by George Thomson:<br /><br /><blockquote>He to wisdom leadeth man,<br />He hath stablished firm the law,<br />Man shall learn by suffering.<br />When deep slumber falls, remembered sins<br />Chafe the sore heart with fresh pain, and no<br />Welcome wisdom meets within.<br />Harsh the grace dispensed by powers immortal<br />On the awful bench enthroned.</blockquote><br /><br />I do not know why it is so different, but it makes me want to read the translation quoted by RFK, which is far more beautiful:<br /><br /><blockquote>Even in our sleep, pain which cannot forget<br />falls drop by drop upon the heart,<br />until, in our own despair,<br />against our will,<br />comes wisdom<br />through the awful grace of God. </blockquote><br /><br />The Orestia is a story about the cycle of revenge if sought out, and that wisdom is necessarily predicated by suffering. <br /><br />There is something supremely profound about RFK’s spontaneous recall of this verse given standing in the back of a pickup truck to calm a crowd that the police had already told him they could not protect him from should things turn for the worst. I had never read really any ancient literature before. I imagine that there is something about enduring art like this that can be the only refuge for a brother who witnesses the assassination of his brother, the president. What I learned from being so deeply affected by his speech is that appreciation of literature and any art that speaks to you can land years later. Books we read when fearful or songs that comfort us when depressed — wisdom from suffering — become building blocks for passing along comfort and clarity to others at the right moment.",
    "cover": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1320493129l/1530.jpg",
    "link": "https://www.goodreads.com/review/show/8534855590",
    "readAt": "Wed, 22 Apr 2026 00:00:00 +0000",
    "year": "-458",
    "pages": "127",
    "color": "#5b3a29",
    "thickness": 29,
    "yearRead": "2026"
  },
  {
    "title": "Careless People: A Cautionary Tale of Power, Greed, and Lost Idealism",
    "author": "Sarah Wynn-Williams",
    "rating": 4,
    "review": "Pretty good read. There are only a few anecdotes in here that weren’t already well known that will surprise readers. If you are expecting this to be a shocking tell-all, it really isn’t quite that.<br /><br />That said, I think the core takeaway is that the experience of seeing how the sausage is made is never going to be good. Powerful people who make decisions are often overwhelmingly careless and unfeeling. This book reminds me of the very worst of corporate culture that can manifest at any organization irrespective of its size. I don’t know how this will ever change if every company has to show constant growth. The most sociopathic among us will always rise to meet that.<br /><br />I don’t find all of the author’s anecdotes to be completely believable. I saw another reviewer mention that many of her statements read like comebacks you think of in the shower after the argument and it was very true to my experience reading this. A memoir rife with a lot of pointed dialogue, rather than being mainly introspective, can have this effect even if it’s all true, so who’s to say?",
    "cover": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1742029683l/223436601._SY475_.jpg",
    "link": "https://www.goodreads.com/review/show/8474868055",
    "readAt": "Sat, 18 Apr 2026 00:00:00 +0000",
    "year": "2025",
    "pages": "382",
    "color": "#4a3b5c",
    "thickness": 41,
    "yearRead": "2026"
  },
  {
    "title": "War and Peace",
    "author": "Leo Tolstoy",
    "rating": 5,
    "review": "In general I go by: “good things are good” — I feel like people sometimes avoid what is commonly referred to as the best for whatever reason. I think it’s a lot better to just see what all the fuss is about. <br /><br />War and Peace is widely considered one of the greatest novels ever written and it is immediately clear early on into the story. The story just flows so well and while tragic events unfold unceasingly, I’ve never felt more drawn to characters like I was here. <br /><br />In my feeling the book presented a hero composed of two people in Prince Andrew and Pierre Bezhukov. It is difficult to believe in a singular hero, they say to “never meet your heroes” for a reason and even when a novel presents a flawed character who becomes a hero, it feels off. In presenting these two as friends from early on in childhood and how unique that kind of connection is that it can exist across battlefields and years of zero contact, in presenting their flawed decisions and guidance of each other, in presenting their widely divergent lives during a tumultuous time, Tolstoy creates a perfect composite hero in my view. <br /><br />This is 5 stars for me but a couple things I didn’t like: <br /><br />(1) The randomly interspersed giant sections that struck me as rambling by Tolstoy about history and Napoleon. I don’t know enough about the time to say anything conclusively, but if you bring up “the historians” as a monolith what feels like several hundred times throughout the fantastic story, it seems like you are trying to revise history without the benefit of facts. And he gets extremely philosophical at times in a way I couldn’t follow. The entire second epilogue is this and I just didn’t enjoy it, despite loving the story. <br /><br />(2) At one point the characters describe Sonya as basically not an individual person capable of real feeling. What I like about Russian literature is that it has a way of highlighting the deepest feelings that exist in everyone, and it felt like they tried to explain away a character being hard done by a very sad situation as non sentient <br /><br />I’ll end this review with a quote I liked. There are plenty more in the book but this one I saved as it came at an important inflection point in the story:<br /><br />&gt; We imagine that when we are thrown out of our usual ruts all is lost, but it is only then that what is new and good begins. While there is life there is happiness.",
    "cover": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1489799557l/384208._SY475_.jpg",
    "link": "https://www.goodreads.com/review/show/8427759542",
    "readAt": "Mon, 13 Apr 2026 00:00:00 +0000",
    "year": "1868",
    "pages": "1736",
    "color": "#1f3a5f",
    "thickness": 60,
    "yearRead": "2026"
  },
  {
    "title": "The Count of Monte Cristo",
    "author": "Lowell Bair",
    "rating": 5,
    "review": "",
    "cover": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1348011047l/522110.jpg",
    "link": "https://www.goodreads.com/review/show/7630842081",
    "readAt": "",
    "year": "1846",
    "pages": "531",
    "color": "#6b4226",
    "thickness": 48,
    "yearRead": ""
  },
  {
    "title": "Persuasion",
    "author": "Jane Austen",
    "rating": 3,
    "review": "I may not be a Jane Austen fan but I am told that I do not understand all of the subtleties. It is enjoyable to read with a British accent in your head though",
    "cover": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1349080701l/468004.jpg",
    "link": "https://www.goodreads.com/review/show/8063497987",
    "readAt": "Wed, 12 Nov 2025 00:00:00 +0000",
    "year": "1817",
    "pages": "325",
    "color": "#3d5a3d",
    "thickness": 38,
    "yearRead": "2025"
  },
  {
    "title": "The Brothers Karamazov",
    "author": "Fyodor Dostoevsky",
    "rating": 5,
    "review": "This book left me feeling somehow simultaneously less and more knowledgeable of what life is truly about, and I was neither aware that this was possible nor that this is a feeling I would enjoy.",
    "cover": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1657562621l/138502._SY475_.jpg",
    "link": "https://www.goodreads.com/review/show/8063479421",
    "readAt": "Wed, 15 Oct 2025 00:00:00 +0000",
    "year": "1879",
    "pages": "840",
    "color": "#742d3a",
    "thickness": 60,
    "yearRead": "2025"
  },
  {
    "title": "The Trial",
    "author": "Franz Kafka",
    "rating": 1,
    "review": "This book sucked. I’m sure there is some greater philosophical point about the powerlessness we face in life that is intended here but it was beyond me.<br /><br />I’ve heard complaints people have about how the legal system can feel imposing, impersonal, and paradoxically also very silly when you are subject to it, and this honestly felt like the author just had that experience with some kind of court case and used this book to gripe about it. He should’ve just talked it over with someone over a beer, which would’ve saved me reading this weird snoozefest just so I could use the word Kafkaesque without feeling like an imposter.",
    "cover": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1320552031l/618559.jpg",
    "link": "https://www.goodreads.com/review/show/8106594409",
    "readAt": "Sun, 8 Mar 2026 00:00:00 +0000",
    "year": "1925",
    "pages": "286",
    "color": "#34495e",
    "thickness": 37,
    "yearRead": "2026"
  },
  {
    "title": "Second Foundation (Foundation, #3)",
    "author": "Isaac Asimov",
    "rating": 5,
    "review": "",
    "cover": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1661015922l/29580._SY475_.jpg",
    "link": "https://www.goodreads.com/review/show/8280816484",
    "readAt": "Wed, 28 Jan 2026 00:00:00 +0000",
    "year": "1953",
    "pages": "256",
    "color": "#5c4033",
    "thickness": 35,
    "yearRead": "2026"
  },
  {
    "title": "The Stranger",
    "author": "Albert Camus",
    "rating": 4,
    "review": "",
    "cover": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1361537642l/37506.jpg",
    "link": "https://www.goodreads.com/review/show/8275946383",
    "readAt": "Sun, 18 Jan 2026 00:00:00 +0000",
    "year": "1942",
    "pages": "117",
    "color": "#2e4d4d",
    "thickness": 29,
    "yearRead": "2026"
  },
  {
    "title": "Foundation and Empire (Foundation, #2)",
    "author": "Isaac Asimov",
    "rating": 4,
    "review": "",
    "cover": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1391454612l/29581.jpg",
    "link": "https://www.goodreads.com/review/show/8250580487",
    "readAt": "Sun, 11 Jan 2026 00:00:00 +0000",
    "year": "1952",
    "pages": "256",
    "color": "#603b2e",
    "thickness": 35,
    "yearRead": "2026"
  },
  {
    "title": "The Idiot",
    "author": "Fyodor Dostoevsky",
    "rating": 3,
    "review": "I really enjoyed The Brothers Karamazov and read that The Idiot was similar. I hoped that The Idiot would build on some of the themes introduced by Aloysha in TBK. The book left me very disappointed as a result. Prince Myshkin felt like a very primitive version of Aloysha which makes sense as the book was written before TBK, but I honestly don’t know if I would’ve picked TBK up quickly after this. It just felt very muted.<br /><br />Myshkin was just a completely neutral element in everything. I can appreciate the value in forgiveness and mercy which I believe is the main point here, but it was very frustrating to see Myshkin only take life as it comes to him. There is no analogue to the side story of Aloysha guiding the group of young kids and all of the beautiful details that come from that simple detour from the main story.<br /><br />It’s possible that Dostoyevsky meant to highlight something here: that it isn’t enough to be meek, forgiving, and kind. You must also have a backbone or these virtues mean little. I am not sure. <br /><br />Additionally, this felt much different from other Dostoyevsky books. It felt disorganized and at times lacking a lot of substance. For me, not an essential read.",
    "cover": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1320437439l/525407.jpg",
    "link": "https://www.goodreads.com/review/show/8063499920",
    "readAt": "Sat, 27 Dec 2025 00:00:00 +0000",
    "year": "1869",
    "pages": "633",
    "color": "#3a3d5c",
    "thickness": 52,
    "yearRead": "2025"
  },
  {
    "title": "Notes from Underground",
    "author": "Fyodor Dostoevsky",
    "rating": 3,
    "review": "",
    "cover": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1657562701l/18809._SY475_.jpg",
    "link": "https://www.goodreads.com/review/show/8063499829",
    "readAt": "Wed, 26 Nov 2025 00:00:00 +0000",
    "year": "1864",
    "pages": "126",
    "color": "#4d2e3a",
    "thickness": 29,
    "yearRead": "2025"
  },
  {
    "title": "The Master and Margarita",
    "author": "Mikhail Bulgakov",
    "rating": 4,
    "review": "Generally a very good read. A lot of passages flowed so well that I was shocked at how I could fly through them. I’d go back to reread and found that I understood it the first time through, certainly a testament to Bulgakov’s mastery of the written word if this can happen even after a translation from Russian to English. <br /><br />The story had an unsettling nature to it, I think by intention of course. There were some unexpectedly charming characters and moments. Although I found the story engaging and thought that the final takeaways were interesting and meaningful, I am glad to be finished and no longer engrossed in the world of this book.",
    "cover": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1562368093l/525929.jpg",
    "link": "https://www.goodreads.com/review/show/8063499181",
    "readAt": "Sat, 22 Nov 2025 00:00:00 +0000",
    "year": "1967",
    "pages": "446",
    "color": "#26413c",
    "thickness": 44,
    "yearRead": "2025"
  },
  {
    "title": "Foundation (Foundation, #1)",
    "author": "Isaac Asimov",
    "rating": 4,
    "review": "",
    "cover": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1417900846l/29579.jpg",
    "link": "https://www.goodreads.com/review/show/8063528231",
    "readAt": "",
    "year": "1951",
    "pages": "244",
    "color": "#4a4031",
    "thickness": 35,
    "yearRead": ""
  },
  {
    "title": "Anna Karenina",
    "author": "Leo Tolstoy",
    "rating": 5,
    "review": "",
    "cover": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1376941854l/18306723.jpg",
    "link": "https://www.goodreads.com/review/show/7630836287",
    "readAt": "Sat, 13 Sep 2025 00:00:00 +0000",
    "year": "1878",
    "pages": "864",
    "color": "#553344",
    "thickness": 60,
    "yearRead": "2025"
  },
  {
    "title": "The King and Queen of Malibu: The True Story of the Battle for Paradise",
    "author": "David K. Randall",
    "rating": 5,
    "review": "",
    "cover": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1464994911l/30231798.jpg",
    "link": "https://www.goodreads.com/review/show/7630833875",
    "readAt": "",
    "year": "2016",
    "pages": "272",
    "color": "#2d3a4a",
    "thickness": 36,
    "yearRead": ""
  },
  {
    "title": "Liar's Poker",
    "author": "Michael   Lewis",
    "rating": 4,
    "review": "",
    "cover": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1348906209l/7865083.jpg",
    "link": "https://www.goodreads.com/review/show/7630837615",
    "readAt": "",
    "year": "1989",
    "pages": "310",
    "color": "#473d2e",
    "thickness": 38,
    "yearRead": ""
  },
  {
    "title": "Carrying the Fire: An Astronaut's Journey",
    "author": "Michael  Collins",
    "rating": 4,
    "review": "",
    "cover": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1347311290l/612456.jpg",
    "link": "https://www.goodreads.com/review/show/7630838389",
    "readAt": "",
    "year": "1974",
    "pages": "478",
    "color": "#3e2d4a",
    "thickness": 45,
    "yearRead": ""
  },
  {
    "title": "Zero to One: Notes on Startups, or How to Build the Future",
    "author": "Peter Thiel",
    "rating": 3,
    "review": "",
    "cover": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1630663027l/18050143.jpg",
    "link": "https://www.goodreads.com/review/show/7630840695",
    "readAt": "",
    "year": "2014",
    "pages": "195",
    "color": "#2d4742",
    "thickness": 32,
    "yearRead": ""
  }
];
